### ISSUE TITLE
Emulate Physical Files & Folders

### ISSUE THREAD

**Issue by christlin** [seanox/apiDAV#2] opened 2023-06-07 17:59 UTC
Hi, I would like to emulate files and directories from a given path. Is this possible with this implementation?

In your previous issue i can see some variable can be included in the path, however my requirement is something like sharing the server side documents over webdav. So i find @WebDavMapping's path is little limiting factor.

Let me know if there is an workaround for this, thanks!

**Comment by seanox** [comment] 2023-06-08 05:31
Hello Christlin,
I still do not fully understand the requirement.
In general, directories and files can be emulated. @WebDavMapping supports unrestricted" path structures in any depth.

There are only two requirements:
- path must be fixed with the start of the application in the annotation
- path must be unique

About: sharing the server side documents over webdav -- is that what you mean?
```
+ directoryA
  - fileA (real / web share / sharepoint)
  - fileB (real / web share / sharepoint)
  - fileC (spring boot)
  - fileD (real / web share / sharepoint)
  - fileE (real / web share / sharepoint)
  - ...
+ directoryB
  - fileF (real / web share / sharepoint)
  - fileD (spring boot)
  - ...
+ ...  
```
This can also be done via routes/forwardings with an upstream web server or the WebDAV servlet acts as a reverse proxy.

Feel free to let me know more details about your requirement.

Best regards, Simon

**Comment by seanox** [comment] 2023-06-29 19:53
Since no further response, the issue is closed.

**Closed as completed** 2023-06-29 19:53 UTC
